CXXFLAGS=-Wall -DSC_INCLUDE_DYNAMIC_PROCESSES
EXE_NAME=readfile
SYSTEMC_HOME=/usr/local/systemc-2.3.2

all: rel

rel: OPTFLAGS = -O3

rel: $(EXE_NAME)

dbg: OPTFLAGS = -O0 -g

dbg: $(EXE_NAME)

.PHONY: dbg rel


CXXFLAGS+=$(OPTFLAGS)


SRC = $(wildcard *.cpp)
OBJ = $(addsuffix .o, $(basename $(SRC)))
INCLUDES= -I$(SYSTEMC_HOME)/include
LIBS= -L$(SYSTEMC_HOME)/lib-linux64 $(SYSTEMC_HOME)/lib-linux64/libsystemc.so  -lm -pthread -Wl,-rpath -Wl,$(SYSTEMC_HOME)/lib-linux64

REBUILDABLES=$(OBJ) $(EXE_NAME)

#   $@ target name, $^ target deps, $< matched pattern
$(EXE_NAME): $(OBJ)
	$(CXX) $(CXXFLAGS) $(LIBS) -o $@ $^ 
	@echo "Built $@ successfully" 

#include the autogenerated dependency files for each .o file
-include $(OBJ:.o=.dep)

# build dependency list via gcc -M and save to a .dep file
%.dep : %.cpp
	@$(CXX) -M $(CXXFLAGS) $(INCLUDES) $< > $@

# build all .cpp files to .o files
%.o : %.cpp
	g++ $(CXXFLAGS) $(INCLUDES) -o $@ -c $<

clean: 
	-rm -f $(REBUILDABLES) *.dep

sim:
	./$(EXE_NAME)

gdb:
	gdb ./$(EXE_NAME)
